name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: rystei
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          message: "Generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
